#!/usr/bin/env python3
"""Build-time codegen for src/api/unicode_tables.inc.

Emits compact C++ interval/lookup tables needed by the tokenizer:
  - general-category intervals for \\p{L}, \\p{M}, \\p{N}
  - White_Space property intervals (regex crate `\\s` semantics)
  - canonical (NFC) data: single-level canonical decompositions,
    canonical combining classes, and the canonical composition pairs
    (composition exclusions are handled empirically: a pair (a,b) -> c is
    only emitted if unicodedata.normalize('NFC', a+b) == c).

Uses only Python's unicodedata. Re-run and commit the output; do not edit
the generated file by hand.
"""

import sys
import unicodedata

UNIDATA = unicodedata.unidata_version
MAX_CP = 0x110000

# Unicode White_Space property (stable list; matches Rust regex `\s`).
WHITE_SPACE = [
    *range(0x0009, 0x000E), 0x0020, 0x0085, 0x00A0, 0x1680,
    *range(0x2000, 0x200B), 0x2028, 0x2029, 0x202F, 0x205F, 0x3000,
]
WS_SET = set(WHITE_SPACE)


def intervals(pred):
    out = []
    start = None
    for cp in range(MAX_CP):
        if pred(cp):
            if start is None:
                start = cp
            prev = cp
        elif start is not None:
            out.append((start, prev))
            start = None
    if start is not None:
        out.append((start, prev))
    return out


def main():
    cat = [unicodedata.category(chr(cp)) for cp in range(MAX_CP)]

    tab_l = intervals(lambda cp: cat[cp][0] == "L")
    tab_m = intervals(lambda cp: cat[cp][0] == "M")
    tab_n = intervals(lambda cp: cat[cp][0] == "N")
    tab_ws = intervals(lambda cp: cp in WS_SET)

    # Canonical combining class: merge consecutive cps sharing a value.
    ccc_raw = [(cp, unicodedata.combining(chr(cp))) for cp in range(MAX_CP)]
    tab_ccc = []
    for cp, v in ccc_raw:
        if not v:
            continue
        if tab_ccc and tab_ccc[-1][1] == cp - 1 and tab_ccc[-1][2] == v:
            tab_ccc[-1][1] = cp
        else:
            tab_ccc.append([cp, cp, v])

    # Single-level canonical decompositions (skip compatibility mappings).
    decomp = {}
    for cp in range(MAX_CP):
        d = unicodedata.decomposition(chr(cp))
        if d and not d.startswith("<"):
            decomp[cp] = [int(x, 16) for x in d.split()]

    # Canonical composition pairs, derived empirically so that composition
    # exclusions are handled without needing CompositionExclusions.txt.
    # Hangul is excluded (handled algorithmically in C++).
    # The C++ side binary-searches this table on (a, b), so it must be sorted
    # by (a, b) -- NOT by the composed codepoint.
    comp = []
    for cp, parts in sorted(decomp.items()):
        if len(parts) != 2 or 0xAC00 <= cp < 0xAC00 + 11172:
            continue
        a, b = parts
        if unicodedata.normalize("NFC", chr(a) + chr(b)) == chr(cp):
            comp.append((a, b, cp))
    comp.sort(key=lambda t: (t[0], t[1]))

    # Flatten decomposition payload.
    decomp_data = []
    decomp_idx = []
    for cp, parts in sorted(decomp.items()):
        decomp_idx.append((cp, len(decomp_data), len(parts)))
        decomp_data.extend(parts)

    lines = []
    w = lines.append
    w("// Auto-generated by tools/gen_unicode_tables.py — do not edit.")
    w(f"// Unicode data version: {UNIDATA}")
    w("#pragma once")
    w("#include <cstddef>")
    w("#include <cstdint>")
    w("")
    w("namespace gdec_uni {")
    w("")

    def emit_intervals(name, tab):
        w(f"static const uint32_t {name}[][2] = {{")
        for lo, hi in tab:
            w(f"    {{0x{lo:X}u, 0x{hi:X}u}},")
        w("};")
        w(f"static const size_t {name}Count = {len(tab)};")
        w("")

    emit_intervals("kCatL", tab_l)
    emit_intervals("kCatM", tab_m)
    emit_intervals("kCatN", tab_n)
    emit_intervals("kWhiteSpace", tab_ws)

    w("struct CCCEntry { uint32_t lo, hi; uint8_t ccc; };")
    w("static const CCCEntry kCCC[] = {")
    for lo, hi, v in tab_ccc:
        w(f"    {{0x{lo:X}u, 0x{hi:X}u, {v}}},")
    w("};")
    w(f"static const size_t kCCCCount = {len(tab_ccc)};")
    w("")

    w("struct DecompEntry { uint32_t cp; uint32_t off; uint16_t len; };")
    w("static const DecompEntry kDecomp[] = {")
    for cp, off, ln in decomp_idx:
        w(f"    {{0x{cp:X}u, {off}u, {ln}}},")
    w("};")
    w(f"static const size_t kDecompCount = {len(decomp_idx)};")
    w("static const uint32_t kDecompData[] = {")
    row = []
    for v in decomp_data:
        row.append(f"0x{v:X}u")
        if len(row) == 12:
            w("    " + ", ".join(row) + ",")
            row = []
    if row:
        w("    " + ", ".join(row) + ",")
    w("};")
    w(f"static const size_t kDecompDataCount = {len(decomp_data)};")
    w("")

    w("// Canonical composition pairs sorted by (a, b).")
    w("struct CompEntry { uint32_t a, b, c; };")
    w("static const CompEntry kComp[] = {")
    for a, b, c in comp:
        w(f"    {{0x{a:X}u, 0x{b:X}u, 0x{c:X}u}},")
    w("};")
    w(f"static const size_t kCompCount = {len(comp)};")
    w("")
    w("}  // namespace gdec_uni")

    out_path = sys.argv[1] if len(sys.argv) > 1 else "src/api/unicode_tables.inc"
    with open(out_path, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(
        f"wrote {out_path}: L={len(tab_l)} M={len(tab_m)} N={len(tab_n)} "
        f"WS={len(tab_ws)} ccc={len(tab_ccc)} decomp={len(decomp_idx)} "
        f"comp={len(comp)} (Unicode {UNIDATA})"
    )


if __name__ == "__main__":
    main()
